branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
matrix:
  fast_finish: true
  include:
    - os: osx
      language: cpp
      compiler: clang
      sudo: required
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=osx_xcode
        - DETAILS="libtool"
        - ENABLE_CXX11=1
    - os: linux
      dist: trusty
      compiler: gcc
      language: cpp
      sudo: required
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      services:
        - mongodb
      env:
        - BUILD_NAME=linux_gcc48
        - DETAILS=""
        - ENABLE_CXX11=1
before_install:
  - chmod +x ./doc/ci/travis/${BUILD_NAME}/before_install.sh
  - ./doc/ci/travis/${BUILD_NAME}/before_install.sh

install:
  - chmod +x ./doc/ci/travis/${BUILD_NAME}/install.sh
  - ./doc/ci/travis/${BUILD_NAME}/install.sh
  
script:
  - chmod +x ./doc/ci/travis/${BUILD_NAME}/script.sh
  - ./doc/ci/travis/${BUILD_NAME}/script.sh
notifications:
  email:false
deploy:
  provider: releases
  api_key:
    secure: 9mTUp6xhpsHDutEQePLjEnEitSaTecJ1pFGKNv9bYTbVnT4yQCvUQZrsiijrzPvC
  file: 
    - autofuzslppos_${BUILD_NAME}.zip
  skip_cleanup: true
  overwrite: true
  on:
    repo: lreis2415/AutoFuzSlpPos
    tags: true
    all_branches: true
