branches:
  only:
  - master
matrix:
  fast_finish: true
  include:
    - os: osx
      language: cpp
      compiler: clang
      sudo: required
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=osx_xcode
        - DETAILS="libtool"
        - ENABLE_CXX11=1
    - os: linux
      dist: trusty
      compiler: gcc
      language: cpp
      sudo: required
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      services:
        - mongodb
      env:
        - BUILD_NAME=linux_gcc48
        - DETAILS=""
        - ENABLE_CXX11=1
before_install:
  - ./doc/ci/travis/${BUILD_NAME}/before_install.sh

install:
  - ./doc/ci/travis/${BUILD_NAME}/install.sh

notifications:
  email:false
