version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2010
environment:
  matrix:
    - CMAKE_GENERATOR: "NMake Makefiles"
configuration: Release
clone_folder: c:\zhulj\autofuzslppos
install:
  - ps: Start-FileDownload 'https://download.microsoft.com/download/3/8/D/38D18861-67DE-4E66-92C7-6819D8B07210/mpi_x64.msi'
  - ps: msiexec /i mpi_x64.msi /quiet /qn /norestart
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x64
    
    cd C:\Program Files\Microsoft Windows Performance Toolkit
    
    ls
    
    cd C:\Program Files (x86)\Microsoft Visual Studio 10.0
    
    ls
    
    mpiexec
    
    cd c:\zhulj

    mkdir build

    cd .\build

    cmake -G "NMake Makefiles" c:\zhulj\autofuzslppos\src

    nmake
