version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2015
environment:
  matrix:
    - CMAKE_GENERATOR: "NMake Makefiles"
configuration: Release
clone_folder: c:\zhulj\autofuzslppos
install:
  #- ps: Start-FileDownload 'https://download.microsoft.com/download/3/8/D/38D18861-67DE-4E66-92C7-6819D8B07210/mpi_x64.msi' -- MSMPI 2008 R2
  - ps: Start-FileDownload 'https://download.microsoft.com/download/A/1/3/A1397A8C-4751-433C-8330-F738C3BE2187/mpi_x64.msi'
  - ps: Start-Process "c:\zhulj\autofuzslppos\mpi_x64.msi" -ArgumentList "/qn" -Wait
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
    
    cd c:\zhulj

    mkdir build

    cd .\build

    cmake -G "NMake Makefiles" c:\zhulj\autofuzslppos\src

    nmake
