version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2015
environment:
  matrix:
    - CMAKE_GENERATOR: "NMake Makefiles"
    - CMAKE_GENERATOR: "Visual Studio 12 2015"
configuration: Release
clone_folder: c:\zhulj\autofuzslppos
install:
  - ps: Start-FileDownload 'https://download.microsoft.com/download/3/8/D/38D18861-67DE-4E66-92C7-6819D8B07210/mpi_x64.msi'
  - ps: msiexec /i mpi_x64.msi /passive /qn /norestart
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
    
    cd c:\zhulj

    mkdir build

    cd .\build

    cmake -G "NMake Makefiles" c:\zhulj\autofuzslppos\src

    nmake
