version: AutoFuzSlpPos.{build}
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
image: Visual Studio 2013
configuration: Release
clone_folder: C:\zhulj\autofuzslppos
build:
  parallel: true
  verbosity: minimal
install:
  # install MS-MPI
  - cd C:\zhulj\autofuzslppos
  - "powershell doc\\ci\\appveyor\\install-msmpi.ps1"
  - "doc\\ci\\appveyor\\SetEnvMPI.cmd"
build_script:
  - cd C:\zhulj\autofuzslppos
  # make directory for release
  - mkdir autofuzslppos_win64bit-{branch}\\autofuzslppos\\bin
  - ps: "ls"
  # compile the AutoFuzSlpPos programs
  - mkdir build_64bit
  - cd build_64bit
  - cmake -G "Visual Studio 12 2013 Win64" .. -DARCH=64 -DINSTALL_PREFIX=C:\\zhulj\\autofuzslppos\\autofuzslppos_win64bit-{branch}\\bin
  - msbuild.exe ALL_BUILD.vcxproj /p:Configuration=Release /maxcpucount:4
  - msbuild.exe INSTALL.vcxproj /p:Configuration=Release /maxcpucount:4
  # copy python scripts
  - copy C:\\zhulj\\autofuzslppos\\autofuzslppos\\*.py C:\\zhulj\\autofuzslppos\\autofuzslppos_win64bit-{branch}\\autofuzslppos
  # copy data, test, and manual to release directory
  - xcopy C:\\zhulj\\autofuzslppos\\data C:\\zhulj\\autofuzslppos\\autofuzslppos_win64bit-{branch}\\data /e /c /i /y
  - xcopy C:\\zhulj\\autofuzslppos\\test C:\\zhulj\\autofuzslppos\\autofuzslppos_win64bit-{branch}\\test /e /c /i /y
  - copy C:\\zhulj\\autofuzslppos\\*.pdf C:\\zhulj\\autofuzslppos\\autofuzslppos_win64bit-{branch}
  # check the structure
  - cd C:\\zhulj\\autofuzslppos\\autofuzslppos_win64bit-{branch}
  - ps "ls"
artifacts:
- path: autofuzslppos_win64bit-{branch}
  name: autofuzslppos_win64bit-{branch}
  type: zip
deploy:
- provider: GitHub
  auth_token:
    secure: t0PiVUFL0gHygmnrub8EpUIdVxsyDSVNPeY8qKbWwY65DuNwuUv3ystCZ465EObd
  artifact: autofuzslppos_win64bit-{branch}.zip
  force_update: true
  on:
    appveyor_repo_tag: true