version: AutoFuzSlpPos.{build}
branches:
  only:
  - master
image: Visual Studio 2013
environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
configuration: Release
platform: x64
clone_folder: C:\zhulj\autofuzslppos
build:
  parallel: true
  verbosity: minimal
install:
  # install MS-MPI
  - cd C:\zhulj\autofuzslppos
  - "powershell doc\\ci\\appveyor\\install-msmpi.ps1"
  - "doc\\ci\\appveyor\\SetEnvMPI.cmd"
build_script:
  # make directory for installation
  - mkdir C:\\bin
  - cd C:\zhulj\autofuzslppos\autofuzslppos
  - ps: "ls"
  - mkdir build_64bit
  - cd build_64bit
  - cmake -G "Visual Studio 12 2013 Win64" .. -DARCH=64 -DINSTALL_PREFIX=C:\bin
  - msbuild.exe ALL_BUILD.vcxproj /p:Configuration=Release /maxcpucount:4
  - msbuild.exe INSTALL.vcxproj /p:Configuration=Release /maxcpucount:4

