version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
clone_folder: c:\zhulj\autofuzslppos
build_script:
- cmd: >-
    cd c:\zhulj

    mkdir build

    cd .\build

    cmake -G "NMake Makefiles" c:\zhulj\autofuzslppos

    nmake
